name: PHP Composer and Tests

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build:
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.os }} w/ ${{ matrix.dependencies }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        os: [ubuntu-latest, windows-latest]
        dependencies: ["install", "update"]

    steps:
      - uses: actions/checkout@main

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@main
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer ${{ matrix.dependencies }} --prefer-dist --no-progress --ignore-platform-reqs

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      - name: Run test suite
        env:
          TMPDIR: ${{ runner.temp }}
        run: composer tests
